0.0.1

diff --git a/bin/k8s-cluster b/bin/k8s-cluster
--- a/bin/k8s-cluster
+++ b/bin/k8s-cluster
@@ -1,7 +1,24 @@
 #!/bin/bash
-master="10.171.46.145";
-workers="10.171.46.120 10.171.46.149 10.171.46.166 10.171.46.168";
-case "${1}" in
+plateform="${1:-"devwatt"}";
+action="${2:-"start"}";
+
+case "${plateform}" in
+  "devwatt")
+    master="10.171.46.145";
+    workers="10.171.46.120 10.171.46.149 10.171.46.166 10.171.46.168";
+    ;;
+  "fe")
+    master="72.24.137.246";
+    workers="172.24.137.50 172.24.137.17 172.24.137.219 172.24.137.214";
+    ;;
+  *)
+    echo -e "ERROR: Unknow plateform: \"${plateform}\"";
+    echo -e "Usage: ${0} [devwatt|fe] [start|stop]";
+    exit 1;
+    ;;
+esac
+
+case "${action}" in
   "start")
     echo -e "Cleaning logs: {...";
     k8s-cmd "sudo rm -rf /var/hive/log/* /var/metastore/log/* /var/hdfs/log/* /var/yarn/log/* /var/mapred/log/* /var/hbase/log/* /var/zookeeper/log/* /var/attu7372/log/* /var/ubuntu/log/* /var/impala/log/*";
@@ -103,5 +120,10 @@ case "${1}" in
     echo -e "Stopping zookeeper: {...";
     k8s-cmd "zkServer.sh stop" zookeeper;
     echo -e "}: zookeeper stopped.\n";
+    ;;
+  *)
+    echo -e "ERROR: Unknow action: \"${action}\"";
+    echo -e "Usage: ${0} [devwatt|fe] [start|stop]";
+    exit 1;
     ;;
 esac
diff --git a/bin/k8s-cmd b/bin/k8s-cmd
--- a/bin/k8s-cmd
+++ b/bin/k8s-cmd
@@ -1,9 +1,23 @@
 #!/bin/bash
-user="${2:-"attu7372"}";
-nodes="${3:-"master worker-1 worker-2 worker-3 worker-4"}";
-nodes="${3:-"10.171.46.145 10.171.46.120 10.171.46.149 10.171.46.166 10.171.46.168"}";
+plateform="${4:-"devwatt"}";
+case "${plateform}" in
+  "devwatt")
+    user="${2:-"ubuntu"}";
+    nodes="${3:-"10.171.46.145 10.171.46.120 10.171.46.149 10.171.46.166 10.171.46.168"}";
+    ;;
+  "fe")
+    user="${2:-"diod"}";
+    nodes="${3:-"172.24.137.246 172.24.137.50 172.24.137.17 172.24.137.219 172.24.137.214"}";
+    ;;
+  *)
+    echo -e "ERROR: Unknow plateform: \"${plateform}\"";
+    echo -e "Usage: ${0} {cmd} [user] [nodes] [devwatt|fe]";
+    exit 1;
+    ;;
+esac
+
 for i in ${nodes};
 do
   echo "-- node: ${i} --";
-	ssh -i $HOME/.ssh/devwatt1024 -2XY4Cc aes128-ctr "${user}@${i}" "${1}";
+	ssh -2XY4Cc aes128-ctr "${user}@${i}" "${1}";
 done
diff --git a/bin/k8s-cp b/bin/k8s-cp
--- a/bin/k8s-cp
+++ b/bin/k8s-cp
@@ -1,9 +1,23 @@
 #!/bin/bash
-user="${3:-"attu7372"}";
-nodes="${4:-"master worker-1 worker-2 worker-3 worker-4"}";
-nodes="${4:-"10.171.46.145 10.171.46.120 10.171.46.149 10.171.46.166 10.171.46.168"}";
+plateform="${5:-"devwatt"}";
+case "${plateform}" in
+  "devwatt")
+    user="${3:-"ubuntu"}";
+    nodes="${4:-"10.171.46.145 10.171.46.120 10.171.46.149 10.171.46.166 10.171.46.168"}";
+    ;;
+  "fe")
+    user="${3:-"diod"}";
+    nodes="${4:-"172.24.137.246 172.24.137.50 172.24.137.17 172.24.137.219 172.24.137.214"}";
+    ;;
+  *)
+    echo -e "ERROR: Unknow plateform: \"${plateform}\"";
+    echo -e "Usage: ${0} {cmd} {src} {dest} [user] [nodes] [devwatt|fe]";
+    exit 1;
+    ;;
+esac
+
 for i in ${nodes};
 do
   echo "-- node: ${i} --";
-	scp -i $HOME/.ssh/devwatt1024 -r "${1}" "${user}@${i}:${2}";
+	scp -r "${1}" "${user}@${i}:${2}";
 done
